from dataclasses import dataclass
from arpeggio import PTNodeVisitor
from typing import Optional

from .source_map import SourceMap
from .nodes import *


def _insert_blank_lines(nodes: list) -> list:
    """Insert BlankLine between consecutive CommentLine nodes with a blank line between them.

    Detects the gap by comparing source line numbers: if the next CommentLine
    starts more than one line after the previous one ended, a blank line existed.
    """
    result = []
    prev = None
    for node in nodes:
        if (
            prev is not None
            and isinstance(prev, CommentLine)
            and isinstance(node, CommentLine)
            and getattr(getattr(prev, 'position', None), 'line', None) is not None
            and getattr(getattr(node, 'position', None), 'line', None) is not None
            and node.position.line > prev.position.line + 1
        ):
            result.append(BlankLine(position=node.position))
        result.append(node)
        prev = node
    return result


class _CForParts:
    """Wrapper returned by c_for_inits/c_for_incrs visitors.

    Always truthy so Arpeggio does not drop it from parent children when
    there are zero assignments, and not a list so Arpeggio does not flatten
    it into the parent's children list.
    """
    __slots__ = ('_items',)

    def __init__(self, items: list) -> None:
        self._items = items

    def __iter__(self):
        return iter(self._items)

    def __len__(self) -> int:
        return len(self._items)

    def __bool__(self) -> bool:  # pragma: no cover
        return True


@dataclass
class Position:
    """Represents a location in a source origin.

    Attributes:
        origin: Identifier for the source origin (e.g., file path, "<editor>", etc.)
        line: Line number (1-indexed)
        column: Column number (1-indexed)
        start_offset: 0-based character offset of the token start within the origin's content
        end_offset: 0-based character offset one past the token end within the origin's content
    """
    origin: str
    line: int
    column: int
    start_offset: int = 0
    end_offset: int = 0

    def __repr__(self):
        return f"{self.origin}:{self.line}:{self.column}[{self.start_offset}:{self.end_offset}]"


class SemanticChildren(list):
    """List-like container that supports children.<rule_name> access."""

    def __init__(self, items, rule_map):
        super().__init__(items)
        self._rule_map = rule_map

    def __getattr__(self, name):
        if name == '_rule_map':
            raise AttributeError(name)
        return self._rule_map.get(name, [])

    def __reduce__(self):
        return (list, (list(self),))

    def get_rule(self, rule_name, index=0):
        """Return the index-th result for rule_name, or [] if absent/out of range."""
        results = self._rule_map.get(rule_name, [])
        return results[index] if index < len(results) else []


class ASTBuilderVisitor(PTNodeVisitor):
    """
    Visits the parse tree generated by the PEG grammar in __init__.py and builds the AST defined in ast.py.
    """
    
    def __init__(self, parser, source_map=None, file=""):
        """Initialize the visitor with the parser and optional source map or file path.

        Args:
            parser: The Arpeggio parser instance (needed to access input for position conversion)
            source_map: Optional SourceMap for tracking positions across multiple origins
            file: Optional file path for source location tracking (deprecated, use source_map)
        """
        super().__init__()
        self.parser = parser
        if source_map is not None:
            self.source_map = source_map
            self._has_source_map = bool(source_map._segments)
            self.file = ""  # Not used when source_map is provided
        else:
            # Backward compatibility: create a simple source map from file
            self.source_map = SourceMap()
            self._has_source_map = False
            if file:
                # We can't get the content here, but we'll handle it in _get_node_position
                self.file = file
            else:
                self.file = ""
    
    def visit_parse_tree(self, parse_tree):
        """Visit a parse tree and return the AST.
        
        This is the main entry point for converting a parse tree to an AST.
        
        Args:
            parse_tree: The root node of an Arpeggio parse tree
            
        Returns:
            The root AST node (or list of AST nodes for the root level)
        """
        return self._visit_node(parse_tree)
    
    def _visit_node(self, node):
        """Recursively visit a parse tree node and return AST.
        
        This method handles the visitor pattern for Arpeggio parse trees.
        Terminal nodes are passed through as their values, and NonTerminal nodes
        are visited using their rule_name to find the appropriate visit method.
        NonTerminal nodes without visit methods are passed through as the node itself.
        
        Args:
            node: An Arpeggio parse tree node
            
        Returns:
            The AST node (or list of AST nodes) for this parse tree node,
            or the node/value itself if it should be passed through
        """
        if node is None:
            return None
        
        # Get the rule name for this node
        if not hasattr(node, 'rule_name'):
            # Terminal node - return its value so parent can use it directly
            return getattr(node, 'value', node)
        
        rule_name = node.rule_name
        
        # Visit children first
        # Arpeggio's NonTerminal objects are iterable, so iterate directly
        children = []
        rule_map = {}
        try:
            # Try to iterate over the node (Arpeggio NonTerminal objects are iterable)
            for child in node:
                child_ast = self._visit_node(child)
                if child_ast is not None:
                    child_rule_name = getattr(child, "rule_name", None)
                    if child_rule_name:
                        rule_map.setdefault(child_rule_name, []).append(child_ast)
                    # If child_ast is a list, extend; otherwise append
                    if isinstance(child_ast, list):
                        children.extend(child_ast)
                    else:
                        children.append(child_ast)
        except (TypeError, AttributeError):
            # Node is not iterable, skip children
            pass
        
        children = SemanticChildren(children, rule_map)
        # Call the appropriate visit method
        visit_method_name = f"visit_{rule_name}"
        visit_method = getattr(self, visit_method_name, None)
        if visit_method:
            try:
                result = visit_method(node, children)
                return result
            except Exception as e:
                # If visit method fails, return children or None
                return children if children else None
        else:
            # No visit method - pass through the node itself so parent can access rule_name/value
            # This is useful for operator nodes like TOK_BINARY_OR, TOK_EQUAL, etc.
            return node
    
    def _get_node_end_position(self, node) -> int:
        """Return the combined-string offset one past the last character of node."""
        if node is None:
            return 0
        end = getattr(node, 'position_end', None)
        if end is not None:
            return end
        pos = getattr(node, 'position', 0)
        val = getattr(node, 'value', '')
        return pos + len(str(val))

    def _get_node_position(self, node):
        """Extract position information from an Arpeggio parse tree node.

        Uses SourceMap to map positions back to original origins if available.
        start_offset and end_offset are 0-based offsets within the origin's content.

        Args:
            node: Arpeggio parse tree node

        Returns:
            Position object for the node
        """
        char_pos = getattr(node, 'position', 0)
        end_pos = self._get_node_end_position(node)

        # Use SourceMap if available to map position back to original origin
        if self._has_source_map:
            return self.source_map.get_location(char_pos, end_pos)
        else:
            # Fallback: calculate line/column from character position
            input_str = self.parser.input if hasattr(self.parser, 'input') else ""
            if not input_str or char_pos < 0 or char_pos > len(input_str):
                line = 1
                column = 1
            else:
                text_before = input_str[:char_pos]
                line = text_before.count('\n') + 1
                last_newline = text_before.rfind('\n')
                column = char_pos - last_newline  # 1-indexed

            return Position(
                origin=self.file if self.file else "<unknown>",
                line=line,
                column=column,
                start_offset=char_pos,
                end_offset=end_pos,
            )


    # -- Basic Tokens --

    def visit_TOK_ID(self, node, children):
        # Prefer the last child for value (to avoid list-wrapping problems)
        return Identifier(
            name=str(node.value),
            position=self._get_node_position(node)
        )

    def visit_string_literal(self, node, children):
        # Grammar: single regex matching the full quoted string including quotes.
        # Strip the surrounding double-quotes to get the raw content.
        raw = str(node.value)
        value = raw[1:-1] if raw.startswith('"') and raw.endswith('"') else raw
        return StringLiteral(
            val=value,
            position=self._get_node_position(node)
        )

    def visit_TOK_NUMBER(self, node, children):
        value = children[-1] if children else node.value
        return NumberLiteral(
            val=float(value),
            position=self._get_node_position(node)
        )
    
    def visit_KWD_TRUE(self, node, children):
        return BooleanLiteral(
            val=True,
            position=self._get_node_position(node)
        )

    def visit_KWD_FALSE(self, node, children):
        return BooleanLiteral(
            val=False,
            position=self._get_node_position(node)
        )

    def visit_KWD_UNDEF(self, node, children):
        return UndefinedLiteral(position=self._get_node_position(node))


    # -- Syntactical noise --

    def visit_whitespace_only(self, node, children):
        return None

    def visit_TOK_LOGICAL_OR(self, node, children):
        return '||'

    def visit_TOK_LOGICAL_AND(self, node, children):
        return '&&'

    def visit_TOK_LOGICAL_NOT(self, node, children):
        return None

    def visit_TOK_BINARY_OR(self, node, children):
        return '|'

    def visit_TOK_BINARY_AND(self, node, children):
        return '&'

    def visit_TOK_BINARY_NOT(self, node, children):
        return None

    def visit_TOK_BINARY_SHIFT_LEFT(self, node, children):
        return '<<'

    def visit_TOK_BINARY_SHIFT_RIGHT(self, node, children):
        return '>>'

    def visit_TOK_GT(self, node, children):
        return '>'

    def visit_TOK_LT(self, node, children):
        return '<'

    def visit_TOK_GTE(self, node, children):
        return '>='

    def visit_TOK_LTE(self, node, children):
        return '<='

    def visit_TOK_EQUAL(self, node, children):
        return '=='

    def visit_TOK_NOTEQUAL(self, node, children):
        return '!='

    def visit_TOK_QUESTION(self, node, children):
        return None

    def visit_TOK_ADD(self, node, children):
        return '+'  # For later operator differentiation

    def visit_TOK_SUBTRACT(self, node, children):
        return '-'  # For later operator differentiation

    def visit_TOK_MULTIPLY(self, node, children):
        return '*'  # For later operator differentiation

    def visit_TOK_DIVIDE(self, node, children):
        return '/'  # For later operator differentiation

    def visit_TOK_MODULO(self, node, children):
        return '%'  # For later operator differentiation

    def visit_TOK_EXPONENT(self, node, children):
        return None

    def visit_MOD_SHOW_ONLY(self, node, children):
        return None

    def visit_MOD_HIGHLIGHT(self, node, children):
        return None

    def visit_MOD_BACKGROUND(self, node, children):
        return None

    def visit_MOD_DISABLE(self, node, children):
        return None

    def visit_TOK_DQUOTE(self, node, children):
        return None

    def visit_TOK_BRACE(self, node, children):
        return None

    def visit_TOK_ENDBRACE(self, node, children):
        return None

    def visit_TOK_BRACKET(self, node, children):
        return None

    def visit_TOK_ENDBRACKET(self, node, children):
        return None

    def visit_TOK_COLON(self, node, children):
        return None

    def visit_TOK_SEMICOLON(self, node, children):
        return None

    def visit_TOK_COMMA(self, node, children):
        return None

    def visit_TOK_PERIOD(self, node, children):
        return None

    def visit_TOK_PAREN(self, node, children):
        return None

    def visit_TOK_ENDPAREN(self, node, children):
        return None

    def visit_KWD_MODULE(self, node, children):
        return None

    def visit_KWD_FUNCTION(self, node, children):
        return None

    def visit_KWD_USE(self, node, children):
        return None

    def visit_KWD_INCLUDE(self, node, children):
        return None

    def visit_KWD_IF(self, node, children):
        return None

    def visit_KWD_ELSE(self, node, children):
        return None

    def visit_KWD_FOR(self, node, children):
        return None

    def visit_KWD_INTERSECTION_FOR(self, node, children):
        return None

    def visit_KWD_LET(self, node, children):
        return None

    def visit_KWD_ASSERT(self, node, children):
        return None

    def visit_KWD_ECHO(self, node, children):
        return None

    def visit_KWD_EACH(self, node, children):
        return None

    def visit_TOK_ASSIGN(self, node, children):
        return None

    def visit_TOK_SHOW_ONLY(self, node, children):
        return None

    def visit_TOK_HIGHLIGHT(self, node, children):
        return None

    def visit_TOK_BACKGROUND(self, node, children):
        return None

    def visit_TOK_DISABLE(self, node, children):
        return None


    # --- Parameters ---

    def visit_module_name(self, node, children):
        return children[0] if children else None

    def visit_function_name(self, node, children):
        return children[0] if children else None

    def visit_variable_name(self, node, children):
        return children[0] if children else None

    def visit_module_instantiation_name(self, node, children):
        return children[0] if children else None

    def visit_member_name(self, node, children):
        return children[0] if children else None

    def visit_variable_or_function_name(self, node, children):
        return children[0] if children else None

    def visit_parameter_block(self, node, children):
        # Grammar: (TOK_PAREN, parameters, TOK_ENDPAREN)
        # After visiting: [parameters_list] (TOK_PAREN and TOK_ENDPAREN return None)
        return list(children) if children else []

    def visit_parameters(self, node, children):
        # Grammar: (ZeroOrMore(parameter, sep=TOK_COMMA), ZeroOrMore(TOK_COMMA))
        # Filter out None values (commas) and return list of ParameterDeclaration
        return list(children) if children else []

    def visit_parameter(self, node, children):
        return children[0]

    def visit_parameter_with_default(self, node, children):
        items = list(children)
        name_idx = next((i for i, c in enumerate(items) if isinstance(c, Identifier)), None)
        if name_idx is None:
            name = items[0] if items else None
            default = items[1] if len(items) > 1 else None
            return ParameterDeclaration(name=name, default=default, position=self._get_node_position(node))
        name = items[name_idx]
        leading = [c for c in items[:name_idx] if isinstance(c, (CommentSpan, CommentLine))]
        # trailing: CommentSpan between name and the default expr
        # default is the last Expression that is not the Identifier
        default = next((c for c in reversed(items) if isinstance(c, Expression) and c is not name), None)
        if default is None:
            exprs = children.commentable_expr if hasattr(children, 'commentable_expr') else []
            default = exprs[0] if exprs else None
        default_idx = next((i for i, c in enumerate(items) if c is default), len(items))
        trailing = [c for c in items[name_idx + 1:default_idx] if isinstance(c, (CommentSpan, CommentLine))]
        return ParameterDeclaration(name=name, default=default, leading_comments=leading,
                                    trailing_comments=trailing, position=self._get_node_position(node))

    def visit_parameter_without_default(self, node, children):
        items = list(children)
        name_idx = next((i for i, c in enumerate(items) if isinstance(c, Identifier)), None)
        if name_idx is None:
            name = items[0] if items else None
            if name is None:
                name = Identifier(name=getattr(node, "value", ""), position=self._get_node_position(node))
            return ParameterDeclaration(name=name, default=None, position=self._get_node_position(node))
        name = items[name_idx]
        leading = [c for c in items[:name_idx] if isinstance(c, (CommentSpan, CommentLine))]
        trailing = [c for c in items[name_idx + 1:] if isinstance(c, (CommentSpan, CommentLine))]
        return ParameterDeclaration(name=name, default=None, leading_comments=leading,
                                    trailing_comments=trailing, position=self._get_node_position(node))


    # --- Arguments ---
    
    def visit_argument_block(self, node, children):
        # Grammar: (TOK_PAREN, arguments, TOK_ENDPAREN)
        # After visiting: [arguments_list] (TOK_PAREN and TOK_ENDPAREN return None)
        return list(children) if children else []

    def visit_arguments(self, node, children):
        # Grammar: (ZeroOrMore(argument, sep=TOK_COMMA), Optional(TOK_COMMA))
        # Filter out None values (commas) and return list of Argument
        if hasattr(children, "argument") and children.argument:
            return list(children.argument)
        return [child for child in children if child is not None and isinstance(child, Argument)]  # pragma: no cover

    def visit_argument(self, node, children):
        return children[0]

    def visit_positional_argument(self, node, children):
        return PositionalArgument(expr=children[0], position=self._get_node_position(node))

    def visit_named_argument(self, node, children):
        if hasattr(children, "variable_name") and children.variable_name:
            name = children.variable_name[0]
            exprs = children.commentable_expr or children.expr
            expr = exprs[0] if exprs else None
        else:
            name, expr = children[0], children[1] if len(children) > 1 else None
        return NamedArgument(name=name, expr=expr, position=self._get_node_position(node))

    # --- Module/Function Declarations ---

    def visit_module_definition(self, node, children):
        # Grammar: (KWD_MODULE, ZeroOrMore(comment), module_name, ZeroOrMore(comment), parameter_block, ZeroOrMore(comment), statement)
        # Use rule_map for reliable name/params lookup, flat children for structural comments.
        name = children.module_name[0] if hasattr(children, "module_name") and children.module_name else None
        parameters = children.get_rule("parameter_block") if hasattr(children, "get_rule") else None
        statement = list(children.statement) if hasattr(children, "statement") and children.statement else []
        # Fallback for plain-list children (edge case tests)
        if name is None and not hasattr(children, "module_name"):
            name = children[0] if children else None
            parameters = children[1] if len(children) > 1 else []
        if name is None:
            raise ValueError("module_definition should have a name")
        if parameters is None:
            parameters = []  # pragma: no cover
        if not isinstance(parameters, list):
            parameters = [parameters]  # pragma: no cover
        if not isinstance(statement, list):
            statement = [statement]
        flattened = []
        stack = list(statement)
        while stack:
            item = stack.pop(0)
            if isinstance(item, list):
                stack = item + stack
            elif item is not None:
                flattened.append(item)
        # Extract structural comments using rule_map["comment"] — these are *only*
        # the comments matched by ZeroOrMore(comment) directly in module_definition's
        # grammar (pre-name, post-name, post-params).  Comments from inside the
        # statement_block body appear in rule_map["statement"], not here.
        direct_comments_ids = {id(c) for c in (children.comment if hasattr(children, 'comment') else [])}
        items = list(children)
        name_flat_idx = next((i for i, c in enumerate(items) if c is name), None)
        last_param_flat_idx = max(
            (i for i, c in enumerate(items) if isinstance(c, ParameterDeclaration)),
            default=name_flat_idx if name_flat_idx is not None else -1
        )
        pre_name, post_name, post_params = [], [], []
        if name_flat_idx is not None:
            pre_name = [c for i, c in enumerate(items)
                        if id(c) in direct_comments_ids and i < name_flat_idx]
            post_name = [c for i, c in enumerate(items)
                         if id(c) in direct_comments_ids and name_flat_idx < i <= last_param_flat_idx]
            post_params = [c for i, c in enumerate(items)
                           if id(c) in direct_comments_ids and i > last_param_flat_idx]
        return ModuleDeclaration(name=name, parameters=parameters, children=flattened,
                                 pre_name_comments=pre_name, post_name_comments=post_name,
                                 post_params_comments=post_params,
                                 position=self._get_node_position(node))

    def visit_function_definition(self, node, children):
        # Grammar: (KWD_FUNCTION, ZeroOrMore(comment), function_name, ZeroOrMore(comment),
        #           parameter_block, ZeroOrMore(comment), TOK_ASSIGN, commentable_expr, TOK_SEMICOLON)
        # Use rule_map for reliable name/params/expr lookup, flat children for structural comments.
        name = children.function_name[0] if hasattr(children, "function_name") and children.function_name else None
        parameters = children.get_rule("parameter_block") if hasattr(children, "get_rule") else None
        expr_candidates = (children.commentable_expr or children.expr) if hasattr(children, "commentable_expr") else []
        expr = expr_candidates[0] if expr_candidates else None
        # Fallback for plain-list children (edge case tests)
        if name is None and not hasattr(children, "function_name"):
            name = children[0] if children else None
            parameters = children[1] if len(children) > 1 else []
            expr = children[2] if len(children) > 2 else None
        if name is None:
            raise ValueError("FunctionDeclarationNode should have an Identifier")
        if expr is None:
            raise ValueError("FunctionDeclarationNode should have an Expression")
        if parameters is None:
            parameters = []  # pragma: no cover
        if not isinstance(parameters, list):
            parameters = [parameters]  # pragma: no cover
        # Extract structural comments using rule_map["comment"] — only comments
        # matched directly by ZeroOrMore(comment) in function_definition's grammar
        # (pre-name, post-name, post-params/pre-equals).  Comments from inside
        # commentable_expr are wrapped in CommentedExpr, not individually here.
        direct_comments_ids = {id(c) for c in (children.comment if hasattr(children, 'comment') else [])}
        items = list(children)
        name_flat_idx = next((i for i, c in enumerate(items) if c is name), None)
        last_param_flat_idx = max(
            (i for i, c in enumerate(items) if isinstance(c, ParameterDeclaration)),
            default=name_flat_idx if name_flat_idx is not None else -1
        )
        pre_name, post_name, post_params = [], [], []
        if name_flat_idx is not None:
            pre_name = [c for i, c in enumerate(items)
                        if id(c) in direct_comments_ids and i < name_flat_idx]
            post_name = [c for i, c in enumerate(items)
                         if id(c) in direct_comments_ids and name_flat_idx < i <= last_param_flat_idx]
            post_params = [c for i, c in enumerate(items)
                           if id(c) in direct_comments_ids and i > last_param_flat_idx]
        return FunctionDeclaration(name=name, parameters=parameters, expr=expr,
                                   pre_name_comments=pre_name, post_name_comments=post_name,
                                   post_params_comments=post_params,
                                   position=self._get_node_position(node))
    
    def visit_use_include_file(self, node, children):
        if not children:
            return ""  # pragma: no cover
        # Pick the first non-angle-bracket token as the filepath content
        for child in children:
            value = child.value if hasattr(child, "value") else str(child)
            if value not in ["<", ">"]:
                return str(value)
        return ""  # pragma: no cover

    def visit_use_statement(self, node, children):
        filepath = children.use_include_file[0] if hasattr(children, "use_include_file") and children.use_include_file else (children[0] if children else "")
        if not filepath:
            raise ValueError("UseStatementNode should have a filepath")
        if isinstance(filepath, str):
            filepath = StringLiteral(val=filepath, position=self._get_node_position(node))
        return UseStatement(filepath=filepath, position=self._get_node_position(node))
    
    def visit_include_statement(self, node, children):
        filepath = children.use_include_file[0] if hasattr(children, "use_include_file") and children.use_include_file else (children[0] if children else "")
        if not filepath:
            raise ValueError("IncludeStatementNode should have a filepath")
        if isinstance(filepath, str):
            filepath = StringLiteral(val=filepath, position=self._get_node_position(node))
        return IncludeStatement(filepath=filepath, position=self._get_node_position(node))

    def visit_assignments_expr(self, node, children):
        # Grammar: (ZeroOrMore(assignment_expr, sep=TOK_COMMA), Optional(TOK_COMMA))
        # Filter out None values (commas) and return list of Assignment
        if hasattr(children, "assignment_expr") and children.assignment_expr:
            return list(children.assignment_expr)
        return [child for child in children if child is not None and isinstance(child, Assignment)]  # pragma: no cover
    
    def visit_assignment_expr(self, node, children):
        # Grammar: (ZeroOrMore(comment), variable_name, TOK_ASSIGN, commentable_expr)
        if hasattr(children, "variable_name") and children.variable_name:
            name = children.variable_name[0]
            exprs = children.commentable_expr or children.expr
            expr = exprs[0] if exprs else None
        else:
            if len(children) < 2:
                raise ValueError("assignment_expr should have an Expression child")
            name, expr = children[0], children[1]
        if expr is None:
            raise ValueError("assignment_expr should have an Expression child")
        return Assignment(name=name, expr=expr, position=self._get_node_position(node))
    
    def visit_let_expr(self, node, children):
        # Grammar: (KWD_LET, TOK_PAREN, assignments_expr, TOK_ENDPAREN, commentable_expr)
        # After visiting: [assignments_list, body_expr]
        assignments = children.get_rule("assignments_expr") if hasattr(children, "assignments_expr") else (children[0] if children else [])
        exprs = [c for c in children if isinstance(c, Expression)]
        body = exprs[-1] if exprs else None
        if body is None:
            raise ValueError("let_expr should have an Expression body")
        return LetOp(assignments=assignments, body=body, position=self._get_node_position(node))

    def _build_binop_chain(self, children, node, make_node):
        """Build a left-associative binary op chain, preserving adjacent comments.

        children is the flat list from visit_prec_* (after *_op visitors flatten
        their results). Sequence: expr [comment* op_str comment* expr]*.

        Comments before an operator become trailing comments on the left operand;
        comments after an operator become leading comments on the right operand.
        make_node(left, op_str_or_None, right, position) -> Expression.
        """
        items = list(children)
        if not items:
            raise ValueError("empty binary op chain")
        if len(items) == 1 and isinstance(items[0], Expression):
            return items[0]
        result = items[0]
        i = 1
        while i < len(items):
            pre_comments = []
            while i < len(items) and isinstance(items[i], (CommentSpan, CommentLine)):
                pre_comments.append(items[i]); i += 1
            op_str = None
            if i < len(items) and isinstance(items[i], str):
                op_str = items[i]; i += 1
            post_comments = []
            while i < len(items) and isinstance(items[i], (CommentSpan, CommentLine)):
                post_comments.append(items[i]); i += 1
            if i >= len(items) or not isinstance(items[i], Expression):
                break
            right = items[i]; i += 1
            if pre_comments:
                if isinstance(result, CommentedExpr):
                    result = CommentedExpr(
                        leading_comments=result.leading_comments,
                        trailing_comments=result.trailing_comments + pre_comments,
                        expr=result.expr, position=result.position)
                else:
                    result = CommentedExpr(leading_comments=[], trailing_comments=pre_comments,
                                           expr=result, position=result.position)
            if post_comments:
                if isinstance(right, CommentedExpr):
                    right = CommentedExpr(
                        leading_comments=post_comments + right.leading_comments,
                        trailing_comments=right.trailing_comments,
                        expr=right.expr, position=right.position)
                else:
                    right = CommentedExpr(leading_comments=post_comments, trailing_comments=[],
                                          expr=right, position=right.position)
            result = make_node(result, op_str, right, self._get_node_position(node))
        return result

    # --- Binary operator sub-rules (return list so comments surface to parent) ---

    def visit_logical_or_op(self, node, children):
        return [c for c in children if c is not None]

    def visit_logical_and_op(self, node, children):
        return [c for c in children if c is not None]

    def visit_equality_op(self, node, children):
        return [c for c in children if c is not None]

    def visit_comparison_op(self, node, children):
        return [c for c in children if c is not None]

    def visit_binary_or_op(self, node, children):
        return [c for c in children if c is not None]

    def visit_binary_and_op(self, node, children):
        return [c for c in children if c is not None]

    def visit_binary_shift_op(self, node, children):
        return [c for c in children if c is not None]

    def visit_add_op(self, node, children):
        return [c for c in children if c is not None]

    def visit_mul_op(self, node, children):
        return [c for c in children if c is not None]

    def visit_commentable_expr(self, node, children):
        expr = next((c for c in children if isinstance(c, Expression) and not isinstance(c, (CommentSpan, CommentLine))), None)
        if expr is None:
            return children[0] if children else UndefinedLiteral(position=self._get_node_position(node))
        expr_idx = next(i for i, c in enumerate(children) if c is expr)
        leading = [c for c in children[:expr_idx] if isinstance(c, (CommentSpan, CommentLine))]
        trailing = [c for c in children[expr_idx + 1:] if isinstance(c, (CommentSpan, CommentLine))]
        if leading or trailing:
            return CommentedExpr(
                leading_comments=leading,
                trailing_comments=trailing,
                expr=expr,
                position=self._get_node_position(node),
            )
        return expr

    def visit_assert_expr(self, node, children):
        # Grammar: (KWD_ASSERT, TOK_PAREN, arguments, TOK_ENDPAREN, Optional(commentable_expr))
        arguments = children.get_rule("arguments") if hasattr(children, "arguments") else (children[0] if children else [])
        exprs = [c for c in children if isinstance(c, Expression)]
        body = exprs[-1] if exprs else None
        if body is None:
            body = UndefinedLiteral(position=self._get_node_position(node))
        return AssertOp(arguments=arguments, body=body, position=self._get_node_position(node))

    def visit_echo_expr(self, node, children):
        # Grammar: (KWD_ECHO, TOK_PAREN, arguments, TOK_ENDPAREN, Optional(commentable_expr))
        arguments = children.get_rule("arguments") if hasattr(children, "arguments") else (children[0] if children else [])
        exprs = [c for c in children if isinstance(c, Expression)]
        body = exprs[-1] if exprs else None
        if body is None:
            body = UndefinedLiteral(position=self._get_node_position(node))
        return EchoOp(arguments=arguments, body=body, position=self._get_node_position(node))
    
    def visit_ternary_expr(self, node, children):
        # Grammar: (prec_logical_or, TOK_QUESTION, commentable_expr, TOK_COLON, commentable_expr)
        # After visiting: [condition, true_expr, false_expr] — flat list of Expression nodes;
        # TOK_QUESTION and TOK_COLON return None (filtered out).
        exprs = [c for c in children if isinstance(c, Expression)]
        if len(exprs) < 3:
            raise ValueError("ternary_expr should have 3 Expression children (condition, true, false)")
        condition, true_expr, false_expr = exprs[0], exprs[1], exprs[2]
        return TernaryOp(condition=condition, true_expr=true_expr, false_expr=false_expr, position=self._get_node_position(node))
    
    def visit_prec_logical_or(self, node, children):
        return self._build_binop_chain(children, node,
            lambda l, op, r, pos: LogicalOrOp(left=l, right=r, position=pos))

    def visit_prec_logical_and(self, node, children):
        return self._build_binop_chain(children, node,
            lambda l, op, r, pos: LogicalAndOp(left=l, right=r, position=pos))

    def visit_prec_equality(self, node, children):
        def make(l, op, r, pos):
            return InequalityOp(left=l, right=r, position=pos) if op == '!=' else EqualityOp(left=l, right=r, position=pos)
        return self._build_binop_chain(children, node, make)

    def visit_prec_comparison(self, node, children):
        _cmp = {'<': LessThanOp, '>': GreaterThanOp, '<=': LessThanOrEqualOp, '>=': GreaterThanOrEqualOp}
        def make(l, op, r, pos):
            return _cmp.get(op, LessThanOp)(left=l, right=r, position=pos)
        return self._build_binop_chain(children, node, make)

    def visit_prec_binary_or(self, node, children):
        return self._build_binop_chain(children, node,
            lambda l, op, r, pos: BitwiseOrOp(left=l, right=r, position=pos))

    def visit_prec_binary_and(self, node, children):
        return self._build_binop_chain(children, node,
            lambda l, op, r, pos: BitwiseAndOp(left=l, right=r, position=pos))

    def visit_prec_binary_shift(self, node, children):
        def make(l, op, r, pos):
            return BitwiseShiftRightOp(left=l, right=r, position=pos) if op == '>>' else BitwiseShiftLeftOp(left=l, right=r, position=pos)
        return self._build_binop_chain(children, node, make)

    def visit_prec_addition(self, node, children):
        def make(l, op, r, pos):
            return SubtractionOp(left=l, right=r, position=pos) if op == '-' else AdditionOp(left=l, right=r, position=pos)
        return self._build_binop_chain(children, node, make)

    def visit_prec_multiplication(self, node, children):
        _mul = {'*': MultiplicationOp, '/': DivisionOp, '%': ModuloOp}
        def make(l, op, r, pos):
            return _mul.get(op, MultiplicationOp)(left=l, right=r, position=pos)
        return self._build_binop_chain(children, node, make)
    
    def visit_prec_unary(self, node, children):
        # prec_unary rule: (ZeroOrMore(['+', '-', TOK_LOGICAL_NOT, TOK_BINARY_NOT]), prec_exponent)
        # The node structure is: [operator1, operator2, ..., prec_exponent]
        # But Terminal nodes (operators) return None from _visit_node, so we need to access raw children
        exprs = [child for child in children if isinstance(child, Expression)]
        if not exprs:  # pragma: no cover
            raise ValueError("prec_unary should have an Expression child")
        result = exprs[0]
        
        # Get raw node children to access operators
        try:
            node_children = list(node)
            # Operators are all Terminal nodes before the last child (which is prec_exponent)
            ops = []
            for i in range(len(node_children) - 1):  # All but the last child are operators
                operator_node = node_children[i]
                if hasattr(operator_node, 'value'):
                    op = operator_node.value
                elif hasattr(operator_node, 'rule_name'):
                    # Handle TOK_LOGICAL_NOT and TOK_BINARY_NOT
                    if operator_node.rule_name == 'TOK_LOGICAL_NOT':
                        op = '!'
                    elif operator_node.rule_name == 'TOK_BINARY_NOT':
                        op = '~'
                    else:  # pragma: no cover
                        op = str(operator_node)
                else:  # pragma: no cover
                    op = str(operator_node)
                ops.append(op)
            
            # Apply operators right-to-left (last operator first)
            for op in reversed(ops):
                if op == '-':
                    result = UnaryMinusOp(expr=result, position=self._get_node_position(node))
                elif op == '!':
                    result = LogicalNotOp(expr=result, position=self._get_node_position(node))
                elif op == '~':
                    result = BitwiseNotOp(expr=result, position=self._get_node_position(node))
                # '+' does nothing (unary plus)
        except (TypeError, AttributeError, IndexError):
            # Fallback: try to find operators in children (old behavior)
            ops = [child for child in children if isinstance(child, str) and child in ['+', '-', '!', '~']]
            for op in reversed(ops):
                if op == '-':
                    result = UnaryMinusOp(expr=result, position=self._get_node_position(node))
                elif op == '!':  # pragma: no cover
                    result = LogicalNotOp(expr=result, position=self._get_node_position(node))
                elif op == '~':  # pragma: no cover
                    result = BitwiseNotOp(expr=result, position=self._get_node_position(node))
        
        return result
    
    def visit_prec_exponent(self, node, children):
        # prec_exponent rule: [(prec_call, '^', prec_unary), prec_call]
        operands = [child for child in children if isinstance(child, Expression)]
        if len(operands) == 1:
            return operands[0]
        if not operands:  # pragma: no cover
            return children[0] if children else None
        # Right-associative: a^b^c = a^(b^c)
        result = operands[-1]
        for i in range(len(operands) - 2, -1, -1):
            result = ExponentOp(left=operands[i], right=result, position=self._get_node_position(node))
        return result
    
    def visit_prec_call(self, node, children):
        # prec_call rule: (primary, ZeroOrMore([call_expr, lookup_expr, member_expr]))
        if len(children) == 1:
            return children[0]
        result = children[0]
        if not isinstance(result, Expression):
            # If first child is not an Expression, we can't proceed
            return result  # pragma: no cover
        # Process suffixes left-to-right
        # The children after the first are tuples: ('call', args), ('index', expr), or ('member', identifier)
        for i in range(1, len(children)):
            child = children[i]
            if isinstance(child, tuple) and len(child) == 2:
                op_type, op_value = child
                if op_type == 'call':
                    arguments = op_value if isinstance(op_value, list) else [op_value] if isinstance(op_value, Argument) else []
                    result = PrimaryCall(left=result, arguments=arguments, position=self._get_node_position(node))
                elif op_type == 'index':
                    if isinstance(op_value, Expression):
                        result = PrimaryIndex(left=result, index=op_value, position=self._get_node_position(node))
                elif op_type == 'member':
                    if isinstance(op_value, Identifier):
                        result = PrimaryMember(left=result, member=op_value, position=self._get_node_position(node))
            elif isinstance(child, Expression):  # pragma: no cover
                # Fallback: if it's already an Expression, use it directly
                result = child
        return result
    
    def visit_call_expr(self, node, children):
        # call_expr rule: (argument_block,)
        # children already holds argument list items
        return ('call', list(children))
    
    def visit_lookup_expr(self, node, children):
        # lookup_expr rule: (TOK_BRACKET, expr, TOK_ENDBRACKET)
        return ('index', children[0] if children else None)
    
    def visit_member_expr(self, node, children):
        # member_expr rule: (TOK_PERIOD, member_name)
        return ('member', children[0] if children else None)
    
    def visit_paren_expr(self, node, children):
        return children[0]
    
    def visit_primary(self, node, children):
        return children[0]
    
    def visit_range_expr(self, node, children):
        # OpenSCAD syntax: [start:end] or [start:step:end]
        start = children[0]
        if len(children) > 2:
            step = children[1]
            end = children[2]
        else:
            end = children[1]
            step = NumberLiteral(val=1.0, position=self._get_node_position(node))
        return RangeLiteral(start=start, end=end, step=step, position=self._get_node_position(node))
    
    def visit_vector_expr(self, node, children):
        elements = children if children else []
        return ListComprehension(elements=elements, position=self._get_node_position(node))
    
    def visit_funclit_def(self, node, children):
        parameters = [c for c in children if isinstance(c, ParameterDeclaration)]
        body = next(c for c in children if not isinstance(c, ParameterDeclaration))
        return FunctionLiteral(parameters=parameters, body=body, position=self._get_node_position(node))
    
    def visit_vector_elements(self, node, children):
        return list(children) if children else []
    
    def visit_vector_element(self, node, children):
        return children[0]
    
    def visit_listcomp_elements(self, node, children):
        return children[0]

    def visit_listcomp_paren_expr(self, node, children):
        return children[0]
    
    def visit_listcomp_let(self, node, children):
        body = children[-1]
        assignments = [c for c in children[:-1] if isinstance(c, Assignment)]
        return ListCompLet(assignments=assignments, body=body, position=self._get_node_position(node))

    def visit_listcomp_each(self, node, children):
        return ListCompEach(body=children[0], position=self._get_node_position(node))

    def visit_listcomp_for(self, node, children):
        body = children[-1]
        assignments = [c for c in children[:-1] if isinstance(c, Assignment)]
        return ListCompFor(
            assignments=assignments,
            body=body,
            position=self._get_node_position(node)
        )

    def visit_c_for_inits(self, node, children):
        return _CForParts([a for a in children if isinstance(a, Assignment)])

    def visit_c_for_incrs(self, node, children):
        return _CForParts([a for a in children if isinstance(a, Assignment)])

    def visit_listcomp_c_for(self, node, children):
        idx = 0
        inits = list(children[idx]) if isinstance(children[idx], _CForParts) else []
        if isinstance(children[idx], _CForParts):
            idx += 1
        condition = children[idx]; idx += 1
        incrs = list(children[idx]) if idx < len(children) and isinstance(children[idx], _CForParts) else []
        if idx < len(children) and isinstance(children[idx], _CForParts):
            idx += 1
        body = children[idx]
        return ListCompCFor(
            inits=inits,
            condition=condition,
            incrs=incrs,
            body=body,
            position=self._get_node_position(node)
        )
    
    def visit_listcomp_ifelse(self, node, children):
        return ListCompIfElse(
            condition=children[0],
            true_expr=children[1],
            false_expr=children[2],
            position=self._get_node_position(node)
        )

    def visit_listcomp_ifonly(self, node, children):
        return ListCompIf(
            condition=children[0],
            true_expr=children[1],
            position=self._get_node_position(node)
        )
    
    def visit_modular_call(self, node, children):
        name = children[0] if children else None
        if name is None:  # pragma: no cover
            raise ValueError("modular_call should have a module name")
        if not isinstance(name, Identifier):
            name = Identifier(name=str(name), position=self._get_node_position(node))
        arguments = children.get_rule("arguments") if hasattr(children, "get_rule") else (children[1] if len(children) > 1 else [])
        if arguments is None:  # pragma: no cover
            arguments = []
        if not isinstance(arguments, list):  # pragma: no cover
            arguments = [arguments]
        mods = children.get_rule("child_statement") if hasattr(children, "get_rule") else (children[2] if len(children) > 2 else [])
        if mods is None:  # pragma: no cover
            mods = []
        return ModularCall(
            name=name,
            arguments=arguments,
            children=mods,
            position=self._get_node_position(node)
        )
    
    def visit_modular_for(self, node, children):
        assignments = [c for c in children if isinstance(c, Assignment)]
        body = children.get_rule('child_statement')
        return ModularFor(
            assignments=assignments,
            body=body,
            position=self._get_node_position(node)
        )

    def visit_modular_intersection_for(self, node, children):
        assignments = [c for c in children if isinstance(c, Assignment)]
        body = children.get_rule('child_statement')
        return ModularIntersectionFor(assignments=assignments, body=body, position=self._get_node_position(node))

    def visit_modular_let(self, node, children):
        assignments = [c for c in children if isinstance(c, Assignment)]
        mods = children.get_rule('child_statement')
        return ModularLet(assignments=assignments, children=mods, position=self._get_node_position(node))
    
    def visit_modular_echo(self, node, children):
        arguments = [c for c in children if isinstance(c, Argument)]
        mods = children.get_rule('child_statement')
        return ModularEcho(arguments=arguments, children=mods, position=self._get_node_position(node))

    def visit_modular_assert(self, node, children):
        arguments = [c for c in children if isinstance(c, Argument)]
        mods = children.get_rule('child_statement')
        return ModularAssert(arguments=arguments, children=mods, position=self._get_node_position(node))
    
    def visit_if_statement(self, node, children):
        condition = children[0]
        true_branch = children.get_rule('child_statement')
        return ModularIf(condition=condition, true_branch=true_branch, position=self._get_node_position(node))

    def visit_ifelse_statement(self, node, children):
        condition = children[0]
        true_branch = children.get_rule('child_statement')
        false_branch = children.get_rule('child_statement', index=1)
        return ModularIfElse(condition=condition, true_branch=true_branch, false_branch=false_branch, position=self._get_node_position(node))
    
    def visit_modifier_show_only(self, node, children):
        child = children[0]  # We know modifiers can only have one child.
        return ModularModifierShowOnly(child=child, position=self._get_node_position(node))
    
    def visit_modifier_highlight(self, node, children):
        child = children[0]  # We know modifiers can only have one child.
        return ModularModifierHighlight(child=child, position=self._get_node_position(node))
    
    def visit_modifier_background(self, node, children):
        child = children[0]  # We know modifiers can only have one child.
        return ModularModifierBackground(child=child, position=self._get_node_position(node))
    
    def visit_modifier_disable(self, node, children):
        child = children[0]  # We know modifiers can only have one child.
        return ModularModifierDisable(child=child, position=self._get_node_position(node))
    
    def visit_assignment(self, node, children):
        # Grammar: (variable_name, TOK_ASSIGN, expr, TOK_SEMICOLON)
        # After visiting: [Identifier, expr] (TOK_ASSIGN and TOK_SEMICOLON return None)
        return Assignment(name=children[0], expr=children[1], position=self._get_node_position(node))
    
    def visit_comment_line(self, node, children):
        # Grammar: _(r'//.*?$', str_repr='comment')
        # The regex match contains the full comment including //
        text = node.value if hasattr(node, 'value') else (children[0] if children else "")
        # Remove the // prefix if present
        if text.startswith("//"):
            text = text[2:]
        return CommentLine(text=text, position=self._get_node_position(node))
    
    def visit_comment_multi(self, node, children):
        # Grammar: _(r'(?ms)/\*.*?\*/', str_repr='comment')
        # The regex match contains the full comment including /* and */
        text = node.value if hasattr(node, 'value') else (children[0] if children else "")
        # Remove the /* prefix and */ suffix if present
        if text.startswith("/*"):
            text = text[2:]
        if text.endswith("*/"):
            text = text[:-2]
        return CommentSpan(text=text, position=self._get_node_position(node))
    
    def visit_comment(self, node, children):
        return children[0]
    
    def visit_empty_statement(self, node, children):
        return []

    def visit_statement_block(self, node, children):
        return _insert_blank_lines(list(children))

    def visit_statement(self, node, children):
        # Grammar: [empty_statement, statement_block, module_definition, function_definition, module_instantiation, assignment]
        # Return the first child if available
        if not children:
            return None
        if len(children) == 1:
            return children[0]
        return list(children)
    
    def visit_module_instantiation(self, node, children):
        if not children:
            raise ValueError("module_instantiation should have at least one child")
        return children[0]
    
    def visit_single_module_instantiation(self, node, children):
        if not children:
            raise ValueError("single_module_instantiation should have at least one child")
        return children[0]
    
    def visit_child_statement(self, node, children):
        # Grammar: [empty_statement, statement_block, module_instantiation]
        # Return all children as a list. statement_block flattens its contents
        # into children via _visit_node's extend behavior, so we must return all
        # of them rather than just children[0] (which would silently drop siblings).
        return list(children)
    
    def visit_expr(self, node, children) -> Expression:
        if not children:
            raise ValueError("expr should have at least one child")
        return children[0]
    
    def visit_toplevel_statement(self, node, children) -> ASTNode:
        return children[0]
    
    def visit_toplevel_statement_or_comment(self, node, children) -> ASTNode:
        return children[0]
    
    def visit_EOF(self, node, children):
        return None
    
    def visit_openscad_language(self, node, children) -> list[ASTNode]:
        return list(children)

    def visit_openscad_language_with_comments(self, node, children) -> list[ASTNode]:
        return _insert_blank_lines(list(children))

